### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by HemersonTacon** [fitodic/atom-python-docstring#4]
I already installed the package on Atom but couldn't figure out how to use it. I tried to do something like what is did with [this package to VSCode](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) but I did not succeed. Any help would be appreciated!

**Comment by fitodic** [comment]
This package has only one keymap: `ctrl+alt+d`.

By the way, for atom packages you can always check the [JSON](https://github.com/fitodic/atom-python-docstring/blob/master/keymaps/python-docstring.json) file in the `keymaps` directory :wink:
